//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountantReport
    {
        public int ReportID { get; set; }
        public decimal TotalCost { get; set; }
        public int InsuranceCompanyID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual User User { get; set; }
    }
}
