//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzerWork
    {
        public int AnalyzerWorkID { get; set; }
        public int OrderServiceID { get; set; }
        public int AnalyzerID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PerformedAt { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual User User { get; set; }
        public virtual OrderService OrderService { get; set; }
    }
}
