//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderService()
        {
            this.AnalyzerWorks = new HashSet<AnalyzerWork>();
        }
    
        public int OrderServiceID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Barcode { get; set; }
        public string Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalyzerWork> AnalyzerWorks { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
        public virtual Service Service { get; set; }
    }
}
